### ISSUE TITLE
Prints "Could not find any config for exited child..." upon upgrade

### ISSUE THREAD

**Issue by gdb** [stripe/einhorn#46]
I now see this pretty consistently:

```
[MASTER 34636] ERROR: Could not find any config for exited child 34672! This probably indicates a bug in Einhorn.
```

Looks like it was introduced in: https://github.com/stripe/einhorn/commit/673f5a8a6e909766eb7db381dd736b975dc8a8c1. Sounds like we had a race before, but I think this means we have a race still.

@ebroder, what would you think about de-racing by making the state_passer live past the SIGCHLD handler install? I'd guess that would mean either (a) installing the SIGCHLD handle before loading state — though I haven't checked if there's a chicken and an egg there — or (b) having some coordination mechanism between the state_passer and the master. Thoughts?

**Comment by gdb** [comment]
(As a note, looks like this can also be triggered when `can_safely_reload?` returns false.)

**Comment by ebroder** [comment]
Hmm. So my recollection is that I wrote the code in #39 because our einhorn worker monitoring would fire because einhorn would keep the state passer in its state variables indefinitely, thus looking like a very old worker process.

But in any case, it feels like the code in #40 should safely handle all possible cases of this race - it's basically a more generalized and better version of the same issues as #39. Maybe we can revert 673f5a8 now that #40 is in place? We should make sure we think through the state upgrade path before we do, though.

I'm not totally confident all of that is right, though. But intuitively, it seems like a better fix than making the communication with the state passer more complicated.

**Comment by gdb** [comment]
Ah yeah, I like that much better. I'll poke at it.


- gdb

**Comment by adambrakhane** [comment]
Did you guys ever figure out how to resolve this?
